### ISSUE TITLE
Cucumber report gets overwritten if tests are sharded

### ISSUE THREAD

**Issue by calendir** [mattfritz/protractor-cucumber-framework#20]
Hi,

I don't know if any of you encountered this or even if this is the right place to raise this, but when I run my tests and shard them using Protractor then Cucumber's JSON report (I set the output path in the config) gets overwritten every time one of the shards finishes running. Would it be possible to address this?

**Comment by neerjain** [comment]
I also vote up for this issue , this is really required.

**Comment by darrinholst** [comment]
I've handled this by sharding the features myself and giving each results file a unique name. You could have a post build step that merges them all together if your ci tool doesn't allow for multiple results file. We'll need this [pr](https://github.com/mattfritz/protractor-cucumber-framework/pull/19) in order to do that. 

Here's an example of dynamically sharding by feature file - https://github.com/darrinholst/protractor-cucumber-example/blob/master/protractor.conf.js.

I also have a version that shards by scenario so that the shards are all balanced, but that requires protractor to allow file names with line numbers in them - https://github.com/angular/protractor/pull/2754

**Comment by calendir** [comment]
Thank you, Darrin! That's certainly a nifty workaround, but it would be nice to see this being natively supported.

**Comment by mattfritz** [comment]
See comments in PR https://github.com/mattfritz/protractor-cucumber-framework/pull/19, there are side-effects to that implementation with command line flags. I would appreciate suggestions on that PR if you want to chime in. Maybe only support `format` nested attributes since that seems to be the use case?

**Comment by mattfritz** [comment]
Fixed in https://github.com/mattfritz/protractor-cucumber-framework/commit/4a1f2c74a7df51e049ef05f94448b2d931fbcc2d and available in [v0.4.0](https://github.com/mattfritz/protractor-cucumber-framework/releases/tag/v0.4.0)

**Comment by Bill77** [comment]
Hi @mattfritz,

Thanks for merging looking forward to evaluating this, however on [npm registry](https://www.npmjs.com/package/protractor-cucumber-framework) it's not showing v.0.4.0. Is there just a delay or something I'm missing?

TIA,
Bill

**Comment by mattfritz** [comment]
@Bill77 Sorry about that, v0.4.0 should show on NPM now. Thanks!

**Comment by pittgoose** [comment]
@darrinholst in your comment above ([here](https://github.com/mattfritz/protractor-cucumber-framework/issues/20#issuecomment-187756281)) you say:

> I also have a version that shards by scenario so that the shards are all balanced, but that requires protractor to allow file names with line numbers in them - [angular/protractor#2754](https://github.com/angular/protractor/pull/2754)

Could you please share that example, as that PR seems to be merged a while ago.
Thanks!

**Comment by darrinholst** [comment]
It's been a few months since I was on the project that used it, but it should still work...https://gist.github.com/darrinholst/bd00aa0f40d5978a84c47b012215b080
