### ISSUE TITLE
Unit Tests in Step Definitions?

### ISSUE THREAD

**Issue by JimTheMan** [mattfritz/protractor-cucumber-framework#41]
Hi,

I know this project is PROTRACTOR cucumber framework, but I have a situation where I would like to sometimes do protractor "web tests" in my low level step definitions and sometimes implement the step definitions more like "unit tests". 

According to this podcast it is an anti-pattern to have your step definitions be all only web tests:
[https://cucumber.io/blog/2016/05/09/cucumber-antipatterns](https://cucumber.io/blog/2016/05/09/cucumber-antipatterns)

Currently, I can call all regular protractor commands, and I'm using chai for assertions in the web tests. 

Sometimes, however, I would like to use angular-mocks to just inject a controller or filter in a vacuum, without loading up the whole web page and going through the UI. 

Is this possible? I tried it, but I'm getting, a "window is not defined" error from angular-mocks when I try to run it:

```
var chai = require('chai');
var expect = chai.expect;
var inject = require('angular-mocks').inject;
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

var myStepDefinitionsWrapper = function () {

  var myCtrl;

  this.Given(/^Some shiz$/, function (callback) {
    browser.get('/index.html');
    // module('ngNjOrg');

  inject(function ($controller, _mySvc_) {
      var scope = {};
      var mySvc = _mySvc_;
      myCtrl2 = $controller('RegisterController as ctrl', {
        $scope: scope
      });
    });

    callback();
  });

  this.When(/^I do shiz$/, function (callback) {

    // myCtrl.booyah();

    callback();
  });

  this.Then(/^shiz happens\.$/, function (callback) {
    callback();
  });



};
module.exports = myStepDefinitionsWrapper;

```

Thanks!

**Comment by JimTheMan** [comment]
anyone? :'(

**Comment by mattfritz** [comment]
You may be able to use `browser.executeAsyncScript` to inject, but that is not recommended... I don't have time to listen to the podcast, but I looked at the [resulting write up](http://www.thinkcode.se/blog/2016/06/22/cucumber-antipatterns) and didn't see anything about Cuke unit testing? Maybe I missed something?

I would look at using Cucumber in more of a unit test fashion, since Protractor is mainly for end-to-end tests. You wouldn't need Protractor or this framework, and that would allow you to test by component instead of as a whole. See [this article](http://transitioning.to/2012/01/cucumber-and-js-getting-started-with-cucumber-js/) for some first steps. Otherwise it's probably best to use Karma/Jasmine since that's specifically what those tools are built for.

I'm going to close this for now since this isn't core functionality, let me know if you have more info.

**Comment by JimTheMan** [comment]
Hey Matt,

Thanks for getting back to me. Te me, it makes more sense to test the examples of scenarios of how the software is being used with Protractor since it really simulates a user interacting with the it. 

I was thinking it might make sense to use both protractor-cucumber-framework and karma-cucumberjs. Then for each component you have one feature file, but every step definition has a "unit testing implementation" and a "ui test implementation". The karma-cucumber runners were not working for me so I sort of gave up on that idea and went back to traditional karma for unit tests, and this project's framework for "web tests acceptance tests". 

Suppose you have a dropdown box that displays some text on the page and there are 10 possible options. I would think to go for a scenario outline here. In the podcast they don't actually say the phrase "unit testing", but they do say that you shouldn't check scenario outlines with web tests (shortly after 24:00 in the podcast). So my question is then how should I implement scenarios if the only tool I have available to me here is web tests?

Also, it's worrying me a little bit how Protractor really tightly couples the e2e tests (external api calls) and web/ui tests (automating poking stuff as a user would). Is there any benefit using some type of protractor-backend-mocking framework and then having separate to especially if you are running them in parallel on something like Sauce Labs?

Thanks,
Jim
