### ISSUE TITLE
Should Show "specs" Config Variable in Documentation

### ISSUE THREAD

**Issue by JimTheMan** [mattfritz/protractor-cucumber-framework#52]
I'm having a TON of trouble getting this framework to recognize my files. The README currently says to new users to set the framework config variable, and then tells them to go f! themselves. It's critical to mention that you mention that we need to also set the "specs" option in the protractor config file to look for ".feature" and ".step" files. It would also be nice to know how to actually implement the step definitions since every cucumber implementation is different.

**Comment by AlexandrosD** [comment]
I had configured a boilerplate angular2 project (generated with angular-cli) with cucumber.
Have a look at https://github.com/AlexandrosD/ng2-protractor-cucumber

**Comment by JimTheMan** [comment]
@AlexandrosD  Thanks, but what am I supposed to be looking at here? Your karma config file is not even set up to run feature files or step definitions: https://github.com/AlexandrosD/ng2-protractor-cucumber/blob/master/config/karma.conf.js

**Comment by AlexandrosD** [comment]
Nope, I am using cucumber, protractor, and chai there

**Comment by mattfritz** [comment]
Thanks for your help @AlexandrosD 

This configuration is documented in Protractor because it is homogenous to all frameworks (including Jasmine), but I added it in https://github.com/mattfritz/protractor-cucumber-framework/commit/baf47314d6dc70dc4bf20bd97ebdb9afdbed2576 for clarity.

@JimTheMan please try to be more polite when filing issues. This package is simple glue between Protractor and Cucumber, so most of the documentation (such as step definition implementation) is in the [Cucumber docs](https://github.com/cucumber/cucumber-js#support-files).
