### ISSUE TITLE
Update Protractor to 4.0.0

### ISSUE THREAD

**Issue by laurentperroteau** [mattfritz/protractor-cucumber-framework#68]
In version of Protractor actually in use ([3.2.0](https://github.com/angular/protractor/blob/3.2.0/config.json), dated 18/03/2016), Protractor use a buggy version of Chromedriver (2.21), here a [Stackoverflow issue](http://stackoverflow.com/questions/40100960/session-not-created-exception-for-chrome-in-protractor#answer-40101565) ("session not created exception" error).

Protractor solves this with [4.0.0](https://github.com/angular/protractor/blob/4.0.0/CHANGELOG.md) using the webdriver-manager [NPM package](https://www.npmjs.com/package/webdriver-manager).

**Comment by hackel** [comment]
In fact, version 5.0.0 was released one day before you posted this!

**Comment by mattbrunetti** [comment]
I've been using Protractor 5 with this package, since the start of the week, and no issues yet.

**Comment by laurentperroteau** [comment]
The installation documentation only specifies "npm install --save-dev protractor-cucumber-framework", so it's the `protractor-cucumber-framework` package that installs the "protractor" package and because the dependencies it's "^3.2.0", normally you can't install version above major version n°3

**Comment by mattbrunetti** [comment]
@laurentperroteau protractor is actually not in the `"dependencies"` of this package. It's in the `"devDependencies"` so it only gets installed by this package if you are working on or testing this package. I had to install protractor in my package myself, and it's in my package.json.

On that note, technically this package should have protractor under `"peerDependencies"` to prevent the user from using it with incompatible versions of protractor. (But it doesn't seem like there have been any problems with this.)

Updating protractor I assumed meant bumping the version number on [the dev dependency on protractor](https://github.com/mattfritz/protractor-cucumber-framework/blob/master/package.json#L48) so that this package is tested with a more current version of protractor.

**Comment by laurentperroteau** [comment]
@mattbrunetti, thanks you and sorry for the mistake.
